sed -i -e 's/https:\/\/fromthemachine.org/\./g' *.html
sed -i -e 's/https:\/\/www.fromthemachine.org/\./g' *.html
sed -i -e 's/https:\/\/suez.fromthemachine.org/\./g' *.html
sed -i -e 's/https:\/\/lamc.la/\./g' *.html
sed -i -e 's/https:\/\/www.lamc.la/\./g' *.html
sed -i -e 's/https:\/\/en.reallyhim.com/\./g' *.html
sed -i -e 's/https:\/\/127.0.0.1/\./g' *.html
sed -i -e 's/127.0.0.1/\./g' *.html
sed -i -e 's/http:\/\/fromthemachine.org/\./g' *.html
sed -i -e 's/http:\/\/www.fromthemachine.org/\./g' *.html
sed -i -e 's/http:\/\/suez.fromthemachine.org/\./g' *.html
sed -i -e 's/http:\/\/lamc.la/\./g' *.html
sed -i -e 's/http:\/\/www.lamc.la/\./g' *.html
sed -i -e 's/http:\/\/en.reallyhim.com/\./g' *.html
sed -i -e 's/http:\/\/127.0.0.1/\./g' *.html
sed -i -e 's/http:\/\/i.imgur/\.\/i.imgur/g' *.html
sed -i -e 's/https:\/\/i.imgur/\.\/i.imgur/g' *.html
